import frappe

FORM_TOUR_DOC = {
    "dashboard_name": None,
    "docstatus": 0,
    "doctype": "Form Tour",
    "first_document": 0,
    "include_name_field": 0,
    "is_standard": 0,
    "list_name": "List",
    "modified": "2025-02-20 16:10:07.428859",
    "module": "Integrations",
    "name": "Google Calendar Setup",
    "new_document_form": 0,
    "page_name": None,
    "page_route": None,
    "reference_doctype": "Google Calendar",
    "report_name": "",
    "save_on_complete": 1,
    "steps": [
        {
            "child_doctype": None,
            "description": "Ensure Google Calendar is Enabled.",
            "element_selector": None,
            "fieldname": "enable",
            "fieldtype": "Check",
            "has_next_condition": 0,
            "hide_buttons": 0,
            "is_table_field": 0,
            "label": "Enable",
            "modal_trigger": 0,
            "next_form_tour": None,
            "next_on_click": 0,
            "next_step_condition": None,
            "offset_x": 0,
            "offset_y": 0,
            "ondemand_description": None,
            "parent": "Google Calendar Setup",
            "parent_element_selector": None,
            "parent_fieldname": None,
            "parentfield": "steps",
            "parenttype": "Form Tour",
            "popover_element": 0,
            "position": "Bottom",
            "title": "Enable Google Calendar",
            "ui_tour": 0,
        },
        {
            "child_doctype": None,
            "description": "Enter a name to identify your Google Calendar uniquely. It can be something like your name, or <code>Shivam's Calendar</code>",
            "element_selector": None,
            "fieldname": "calendar_name",
            "fieldtype": "Data",
            "has_next_condition": 0,
            "hide_buttons": 0,
            "is_table_field": 0,
            "label": "Calendar Name",
            "modal_trigger": 0,
            "next_form_tour": None,
            "next_on_click": 0,
            "next_step_condition": None,
            "offset_x": 0,
            "offset_y": 0,
            "ondemand_description": None,
            "parent": "Google Calendar Setup",
            "parent_element_selector": None,
            "parent_fieldname": None,
            "parentfield": "steps",
            "parenttype": "Form Tour",
            "popover_element": 0,
            "position": "Bottom",
            "title": "Setup Calendar Name",
            "ui_tour": 0,
        },
        {
            "child_doctype": None,
            "description": "Here, search for the user you belongs to, and select it.",
            "element_selector": None,
            "fieldname": "user",
            "fieldtype": "Link",
            "has_next_condition": 0,
            "hide_buttons": 0,
            "is_table_field": 0,
            "label": "User",
            "modal_trigger": 0,
            "next_form_tour": None,
            "next_on_click": 0,
            "next_step_condition": None,
            "offset_x": 0,
            "offset_y": 0,
            "ondemand_description": None,
            "parent": "Google Calendar Setup",
            "parent_element_selector": None,
            "parent_fieldname": None,
            "parentfield": "steps",
            "parenttype": "Form Tour",
            "popover_element": 0,
            "position": "Top",
            "title": "Select your User",
            "ui_tour": 0,
        },
        {
            "child_doctype": None,
            "description": "For most peoples, this should be kept enabled. It skips checking for All Day Events (Like Working Location) to check for available slots.",
            "element_selector": None,
            "fieldname": "custom_ignore_all_day_events",
            "fieldtype": "Check",
            "has_next_condition": 0,
            "hide_buttons": 0,
            "is_table_field": 0,
            "label": "Ignore All Day Events",
            "modal_trigger": 0,
            "next_form_tour": None,
            "next_on_click": 0,
            "next_step_condition": None,
            "offset_x": 0,
            "offset_y": 0,
            "ondemand_description": None,
            "parent": "Google Calendar Setup",
            "parent_element_selector": None,
            "parent_fieldname": None,
            "parentfield": "steps",
            "parenttype": "Form Tour",
            "popover_element": 0,
            "position": "Bottom",
            "title": "Ignore All Day Events",
            "ui_tour": 0,
        },
        {
            "child_doctype": None,
            "description": 'This calendar will be used to create events.\nYou can keep it blank to use your default calendar.\nIf you want to use a custom calendar, enter the Calendar ID here. (<a href="https://github.com/rtCamp/frappe-appointment/wiki/Google-Calendar-Setup#create-new-google-calendar" target="_blank">Reference</a>)',
            "element_selector": None,
            "fieldname": "google_calendar_id",
            "fieldtype": "Data",
            "has_next_condition": 0,
            "hide_buttons": 0,
            "is_table_field": 0,
            "label": "Google Calendar ID",
            "modal_trigger": 0,
            "next_form_tour": None,
            "next_on_click": 0,
            "next_step_condition": None,
            "offset_x": 0,
            "offset_y": 0,
            "ondemand_description": None,
            "parent": "Google Calendar Setup",
            "parent_element_selector": None,
            "parent_fieldname": None,
            "parentfield": "steps",
            "parenttype": "Form Tour",
            "popover_element": 0,
            "position": "Bottom",
            "title": "Google Calendar ID",
            "ui_tour": 0,
        },
        {
            "child_doctype": None,
            "description": 'Zoom meetings will be scheduled using this email ID for your events (only if Zoom is enabled in <a href="/app/scheduler-settings" target="_blank">Scheduler Settings</a>). \n\nIt defaults to your User Email. If you want to use a custom email for this, please set it here.',
            "element_selector": None,
            "fieldname": "custom_zoom_user_email",
            "fieldtype": "Data",
            "has_next_condition": 0,
            "hide_buttons": 0,
            "is_table_field": 0,
            "label": "Zoom User Email",
            "modal_trigger": 0,
            "next_form_tour": None,
            "next_on_click": 0,
            "next_step_condition": None,
            "offset_x": 0,
            "offset_y": 0,
            "ondemand_description": None,
            "parent": "Google Calendar Setup",
            "parent_element_selector": None,
            "parent_fieldname": None,
            "parentfield": "steps",
            "parenttype": "Form Tour",
            "popover_element": 0,
            "position": "Bottom",
            "title": "Zoom User Email",
            "ui_tour": 0,
        },
    ],
    "title": "Google Calendar Setup",
    "track_steps": 0,
    "ui_tour": 0,
    "view_name": "Workspaces",
    "workspace_name": None,
}


def import_doc():
    frappe.get_doc(FORM_TOUR_DOC).insert(ignore_permissions=True, ignore_if_duplicate=True)
    print("Form Tour Google Calendar Setup Imported")
    return True
